language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 'node'
script:
  - yarn test
after_success:
  - yarn global add codecov
  - codecov
branches:
  only:
    - master
